using System;
using System.Collections.Generic;


using AVcontrol;



namespace JabrAPI.Source
{
    public class Template
    {
        abstract public class IEncryptionKey
        {
            protected readonly string _defaultChars = "`1234567890-=qwertyuiop[]\\asdfghjkl;'zxcvbnm,./~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:\"ZXCVBNM<>?ёйцукенгшщзхъфывапролджэячсмитьбюЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ№";
            protected readonly SecureRandom _random = new(128);  //  Reseed after every 128 generated bytes (min possible amount)

            protected readonly List<Int32> _shifts = [0];
            protected Int32 _shCount = 0;


            public List<Int32> Shifts => _shifts;
            public Int32 ShAmount => _shifts.Count;
            public Int32 ShLength => _shifts.Count;
            public Int32 ShCount => _shifts.Count;



            public void Next()
            {
                try { GenerateAll(); }
                catch { Default(); }
            }



            abstract public string ExportAsString(string splitBy, string splitShifts = " ");
            abstract public string ExportAsString();


            abstract public List<Byte> ExportAsBinaryBE();
            abstract public List<Byte> ExportAsBinaryLE();



            public void SetShiftCount(Int32 count) => _shCount = count;


            abstract public void SetDefault();
            private void Default()
            {
                SetDefault();
                GenerateAll();
            }
            abstract protected private void GenerateAll();



            public void GenerateRandomShifts(Int32 count, Int32 minVal, Int32 maxVal)
            {
                if (count < 0)
                {
                    throw new ArgumentOutOfRangeException
                    (
                        nameof(count),
                        "count cannot be negative"
                    );
                }
                else if (minVal > maxVal)
                {
                    throw new ArgumentException
                    (
                        "min value cannot be greater than max value",
                        "minVal, maxVal"
                    );
                }
                else if (minVal < 0)
                {
                    throw new ArgumentOutOfRangeException
                    (
                        nameof(minVal),
                        "minVal cannot be negative"
                    );
                }

                _shifts.Clear();
                if (count == 0)
                {
                    _shifts.Add(0);
                    return;
                }

                for (var curId = 0; curId < count; curId++)
                    _shifts.Add(_random.Next(minVal, maxVal));
            }
            public void GenerateRandomShifts(Int32 minVal, Int32 maxVal)
                => GenerateRandomShifts(_random.Next(256, 512), minVal, maxVal);
        }
        


    }
}