using System;
using System.Collections.Generic;


using AVcontrol;



namespace JabrAPI.Source
{
    public class Template
    {
        abstract public class IEncryptionKey
        {
            protected readonly string DEFAULT_CHARS = "`1234567890-=qwertyuiop[]\\asdfghjkl;'zxcvbnm,./~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:\"ZXCVBNM<>?ёйцукенгшщзхъфывапролджэячсмитьбюЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ№";
            protected readonly SecureRandom _random = new(128);  //  Reseed after every 128 generated bytes (min possible amount)

            protected readonly List<Int16> _shifts = [0];
            protected Int32 _shCount = 0;


            public List<Int16> Shifts => _shifts;
            public Int32 ShAmount => _shifts == null ? -1 : _shifts.Count;
            public Int32 ShLength => _shifts == null ? -1 : _shifts.Count;
            public Int32 ShCount  => _shifts == null ? -1 : _shifts.Count;



            public void Next(bool resetSettingsToDefaultIfFailed = true, bool throwExceptions = true)
            {
                try
                {
                    GenerateAll();
                }
                catch
                {
                    if (resetSettingsToDefaultIfFailed)
                    {
                        try
                        {
                            Default();
                        }
                        catch
                        {
                            if (throwExceptions) throw;
                        }
                    }
                    else if (throwExceptions) throw;
                }
            }



            abstract public bool   ImportFromString(string data, bool throwExceptions = false);
            abstract public string ExportAsString();



            abstract public bool ImportFromBinary(List<Byte> data, bool throwExceptions = false);
            abstract public List<Byte> ExportAsBinary();



            public void SetShiftCount(Int32 count) => _shCount = count;


            abstract public void SetDefault();
            protected void Default()
            {
                SetDefault();
                GenerateAll();
            }
            abstract protected private void GenerateAll();



            public void GenerateRandomShifts(Int32 count, Int16 minVal, Int16 maxVal)
            {
                if (count < 0)
                {
                    throw new ArgumentOutOfRangeException
                    (
                        nameof(count),
                        "count cannot be negative"
                    );
                }
                else if (minVal > maxVal)
                {
                    throw new ArgumentException
                    (
                        "min value cannot be greater than max value",
                        "minVal, maxVal"
                    );
                }
                else if (minVal < 0)
                {
                    throw new ArgumentOutOfRangeException
                    (
                        nameof(minVal),
                        "minVal cannot be negative"
                    );
                }

                _shifts.Clear();
                if (count == 0)
                {
                    _shifts.Add(0);
                    return;
                }

                for (var curId = 0; curId < count; curId++)
                    _shifts.Add((Int16)_random.Next(minVal, maxVal));
            }
            public void GenerateRandomShifts(Int16 minVal, Int16 maxVal)
                => GenerateRandomShifts(_random.Next(256, 512), minVal, maxVal);
        }

        abstract public class IBinaryKey
        {
            protected readonly Byte[] DEFAULT_BYTES = [ 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
                                                        0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F,
                                                        0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F,
                                                        0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x3B, 0x3C, 0x3D, 0x3E, 0x3F,
                                                        0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4A, 0x4B, 0x4C, 0x4D, 0x4E, 0x4F,
                                                        0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A, 0x5B, 0x5C, 0x5D, 0x5E, 0x5F,
                                                        0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6A, 0x6B, 0x6C, 0x6D, 0x6E, 0x6F,
                                                        0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A, 0x7B, 0x7C, 0x7D, 0x7E, 0x7F,
                                                        0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F,
                                                        0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F,
                                                        0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF,
                                                        0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF,
                                                        0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF,
                                                        0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF,
                                                        0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF,
                                                        0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF ];

            protected readonly SecureRandom _random = new(128);  //  Reseed after every 128 generated bytes (min possible amount)

            protected readonly List<Byte> _shifts = [0];
            protected Byte _shCount = 0;


            public List<Byte> Shifts => _shifts;
            public Int32 ShAmount => _shifts == null ? -1 : _shifts.Count;
            public Int32 ShLength => _shifts == null ? -1 : _shifts.Count;
            public Int32 ShCount  => _shifts == null ? -1 : _shifts.Count;



            public void Next(bool resetSettingsToDefaultIfFailed = true, bool throwExceptions = true)
            {
                try
                {
                    GenerateAll();
                }
                catch
                {
                    if (resetSettingsToDefaultIfFailed)
                    {
                        try
                        {
                            Default();
                        }
                        catch
                        {
                            if (throwExceptions) throw;
                        }
                    }
                    else if (throwExceptions) throw;
                }
            }



            abstract public bool ImportFromBinary(List<Byte> data, bool throwExceptions = false);

            abstract public List<Byte> ExportAsBinary();



            public void SetShiftCount(Byte count) => _shCount = count;


            abstract public void SetDefault();
            protected void Default()
            {
                SetDefault();
                GenerateAll();
            }
            abstract protected private void GenerateAll();



            public void GenerateRandomShifts(Int32 count, Byte minVal, Byte maxVal)
            {
                if (count < 0)
                {
                    throw new ArgumentOutOfRangeException
                    (
                        nameof(count),
                        "count cannot be negative"
                    );
                }
                else if (minVal > maxVal)
                {
                    throw new ArgumentException
                    (
                        "min value cannot be greater than max value",
                        "minVal, maxVal"
                    );
                }
                else if (minVal < 0)
                {
                    throw new ArgumentOutOfRangeException
                    (
                        nameof(minVal),
                        "minVal cannot be negative"
                    );
                }

                _shifts.Clear();
                if (count == 0)
                {
                    _shifts.Add(0);
                    return;
                }

                for (var curId = 0; curId < count; curId++)
                    _shifts.Add(_random.NextByte(minVal, maxVal));
            }
            public void GenerateRandomShifts(Byte minVal, Byte maxVal)
                => GenerateRandomShifts(_random.Next(256, 512), minVal, maxVal);
        }



        public class Noisifier
        {

        }

        public class BinaryNoisifier
        {
            private readonly SecureRandom _random = new(128);  //  Reseed after every 128 generated bytes (min possible amount)

            private readonly List<Byte> _primaryNoise = [];
            private readonly List<Byte> _complexNoise = [];

            private readonly List<Byte> _banned = [];
            private Byte _primaryCount = 8;
            private Byte _complexCount = 16;



            public BinaryNoisifier(List<Byte> primaryNoise, List<Byte> complexNoise)
                => Set(primaryNoise, complexNoise);
            public BinaryNoisifier(BinaryNoisifier otherNoisifier, bool fullCopy = true)
            {
                Set(otherNoisifier.PrimaryNoise, otherNoisifier.ComplexNoise);

                if (fullCopy)
                    SetDefault
                    (
                        otherNoisifier._banned,
                        otherNoisifier._primaryCount,
                        otherNoisifier._complexCount
                    );
            }
            public BinaryNoisifier(List<Byte> banned, bool autoGenerate = true)
            {
                if (autoGenerate) Default(banned);
                else SetDefault(banned);
            }
            public BinaryNoisifier(List<Byte> exported) => ImportFromBinary(exported);
            public BinaryNoisifier()
                => SetDefault();
            


            List<Byte> PrimaryNoise => _primaryNoise;
            List<Byte> ComplexNoise => _complexNoise;
            List<Byte> Banned       => _banned;




            public void Next(bool throwExceptions = true)
            {
                try { GenerateAll(); }
                catch { if (throwExceptions) throw; }
            }
            public void Next(List<Byte> bannedForFailsafeRegeneration,
                bool resetSettingsToDefaultIfFailed = true, bool throwExceptions = true)
            {
                try
                {
                    GenerateAll();
                }
                catch
                {
                    if (resetSettingsToDefaultIfFailed)
                    {
                        try
                        {
                            Default(bannedForFailsafeRegeneration);
                        }
                        catch
                        {
                            if (throwExceptions) throw;
                        }
                    }
                    else if (throwExceptions) throw;
                }
            }
            


            public bool ImportFromBinary(List<Byte> data, bool throwExceptions = false)
            {
                try
                {
                    Byte primaryCount = data[0];
                    if (data.Count < primaryCount + 1)
                    {
                        if (throwExceptions)
                            throw new ArgumentException
                            (
                                $"Data length is insufficient for the specified primaryNoiseCount" +
                                $" {primaryCount} from data[0]",
                                nameof(data)
                            );
                        return false;
                    }

                    _primaryNoise.Clear();
                    _primaryNoise.AddRange(data.GetRange(1, primaryCount));

                    
                    Byte complexCount = data[primaryCount + 1];
                    if (data.Count < complexCount + primaryCount + 2)
                    {
                        if (throwExceptions)
                            throw new ArgumentException
                            (
                                $"Data length is insufficient for the specified complexNoiseCount" +
                                $" {complexCount} from data[{primaryCount + 2}]",
                                nameof(data)
                            );
                        return false;
                    }

                    _complexNoise.Clear();
                    _complexNoise.AddRange(data.GetRange(primaryCount + 2, complexCount));
                }
                catch
                {
                    if (throwExceptions) throw;
                    return false;
                }
                return true;
            }

            public List<Byte> ExportAsBinary()
            {
                List<Byte> result = [];

                result.Add((Byte)(_primaryNoise.Count));
                result.AddRange(_primaryNoise);

                result.Add((Byte)(_complexNoise.Count));
                result.AddRange(_complexNoise);

                return result;
            }



            public void SetDefault(List<Byte> banned, Byte primaryCount = 8, Byte complexCount = 16)
            {
                _banned.Clear();
                _banned.AddRange(banned);

                SetDefault(primaryCount, complexCount);
            }
            public void SetDefault(Byte primaryCount = 8, Byte complexCount = 16)
            {
                _primaryCount = primaryCount;
                _complexCount = complexCount;
            }

            public void SetDefaultOnlyPr(Byte primaryCount = 8)
                => _primaryCount = primaryCount;
            public void SetDefaultOnlyCplx(Byte complexCount = 16)
                => _complexCount = complexCount;

            public void Default(List<Byte> banned)
            {
                SetDefault(banned);
                GenerateAll();
            }
            private void Set(List<Byte> primaryNoise, List<Byte> complexNoise)
            {
                _primaryNoise.Clear();
                _primaryNoise.AddRange(primaryNoise);

                _complexNoise.Clear();
                _complexNoise.AddRange(complexNoise);
            }



            private void GenerateAll()
            {
                GeneratePrimary(false);
                GenerateComplex(true);
            }


            
            private void ReconfigureNoiseParametersCount(Int32 allowedTotal)
            {
                if (allowedTotal < _primaryCount + _complexCount)
                {
                    Byte compromiseLeft = (Byte)(allowedTotal / 3);
                    _primaryCount = compromiseLeft;
                    _complexCount = (Byte)(allowedTotal - compromiseLeft);
                }
            }
            private List<Byte> GetAllowedForDefaultCase(List<Byte> banned, Int32 reconfigureCount)
            {
                ReconfigureNoiseParametersCount(reconfigureCount);

                List<Byte> result = [];
                for (Byte noiseByte = 0; noiseByte < Byte.MaxValue; noiseByte++)
                {
                    if (!banned.Contains(noiseByte)) result.Add(noiseByte);
                }
                return result;
            }
            private List<Byte> GetRemainingAllowedForPrimary(List<Byte> banned, bool banAlreadyUsedInComplex)
            {
                List<Byte> result = [];

                if (!banAlreadyUsedInComplex) result.AddRange(
                    GetAllowedForDefaultCase(banned, 256 - banned.Count));
                else
                {
                    for (Byte noiseByte = 0; noiseByte < Byte.MaxValue; noiseByte++)
                    {
                        if (!banned.Contains(noiseByte) && !_complexNoise.Contains(noiseByte))
                            result.Add(noiseByte);
                    }
                }

                while (result.Count > _primaryCount)
                    result.RemoveAt(_random.Next(result.Count));
                
                return result;
            }
            private List<Byte> GetRemainingAllowedForComplex(List<Byte> banned, bool banAlreadyUsedInPrimary)
            {
                List<Byte> result = [];

                if (!banAlreadyUsedInPrimary) result.AddRange(
                    GetAllowedForDefaultCase(banned, 256 - banned.Count));
                else
                {
                    for (Byte noiseByte = 0; noiseByte < Byte.MaxValue; noiseByte++)
                    {
                        if (!banned.Contains(noiseByte) && !_primaryNoise.Contains(noiseByte))
                            result.Add(noiseByte);
                    }
                }

                while (result.Count > _complexCount)
                    result.RemoveAt(_random.Next(result.Count));

                return result;
            }



            public  List<Byte> GenerateNoise(Byte count, List<Byte> allowed)
            {
                List<Byte> result = [];

                for (var noiseByteId = 0; noiseByteId < count; noiseByteId++)
                {
                    Int32 chosenId = _random.Next(result.Count);
                    result.Insert(chosenId, allowed[noiseByteId]);
                }

                return result;
            }



            public void GeneratePrimary(List<Byte> banned, bool banAlreadyUsedInComplex)
            {
                //  Important to get allowed separately from GenerateNoise
                //  because _primaryCount can change here in default fail case
                List<Byte> allowed = GetRemainingAllowedForPrimary(banned, banAlreadyUsedInComplex);

                _primaryNoise.Clear();
                _primaryNoise.AddRange(GenerateNoise(_primaryCount, allowed));
            }
            public void GeneratePrimary(bool banAlreadyUsedInComplex)
                => GeneratePrimary(_banned, banAlreadyUsedInComplex);

            public void GenerateComplex(List<Byte> banned, bool banAlreadyUsedInPrimary)
            {
                //  Important to get allowed separately from GenerateNoise
                //  because _complexCount can change here in default fail case
                List<Byte> allowed = GetRemainingAllowedForComplex(banned, banAlreadyUsedInPrimary);

                _complexNoise.Clear();
                _complexNoise.AddRange(GenerateNoise(_primaryCount, allowed));
            }
            public void GenerateComplex(bool banAlreadyUsedInComplex)
                => GenerateComplex(_banned, banAlreadyUsedInComplex);
        }
    }
}