using System;
using System.Collections.Generic;


using AVcontrol;
using JabrAPI.Noise;



namespace JabrAPI
{
    public partial class Noisifier
    {
        private readonly SecureRandom _random = new(128);  //  Reseed after every 128 generated bytes (min possible amount)
        public  NoiseSettings settings = new();

        private readonly SetHelper _setHelper;
        private readonly ValidateHelper _validateHelper;

        private string _primaryNoise = "";
        private string _complexNoise = "";

        private readonly List<char> _banned = [];
        private Int32 _primaryCount = 8;
        private Int32 _complexCount = 16;



        public Noisifier(string primaryNoise, string complexNoise)
        {
            _setHelper      = new(this);
            _validateHelper = new(this);

            CopyFrom(primaryNoise, complexNoise);
        }
        public Noisifier(Noisifier otherNoisifier, bool fullCopy = true)
        {
            _setHelper = new(this);
            _validateHelper = new(this);

            CopyFrom(otherNoisifier, fullCopy);
        }
        public Noisifier(List<char> banned, bool autoGenerate = true)
        {
            _setHelper = new(this);
            _validateHelper = new(this);

            if (autoGenerate) DefaultGenerate(banned);
            else Set.Default(banned);
        }
        public Noisifier(List<Byte> exported)
        {
            _setHelper = new(this);
            _validateHelper = new(this);

            ImportFromBinary(exported);
        }
        public Noisifier()
        {
            _setHelper = new(this);
            _validateHelper = new(this);

            Set.Default();
        }
    }
}