using System;
using System.Text;
using System.Linq;
using System.Collections.Generic;


using AVcontrol;
using JabrAPI.Noise;



namespace JabrAPI
{
    public class Noisifier
    {
        private readonly SecureRandom _random = new(128);  //  Reseed after every 128 generated bytes (min possible amount)
        public  NoiseSettings settings = new();

        private string _primaryNoise = "";
        private string _complexNoise = "";

        private readonly List<char> _banned = [];
        private Int32 _primaryCount = 8;
        private Int32 _complexCount = 16;



        public Noisifier(string primaryNoise, string complexNoise)
            => Set(primaryNoise, complexNoise);
        public Noisifier(Noisifier otherNoisifier, bool fullCopy = true)
            => CopyFrom(otherNoisifier, fullCopy);
        public Noisifier(List<char> banned, bool autoGenerate = true)
        {
            if (autoGenerate) DefaultGenerate(banned);
            else SetDefault(banned);
        }
        public Noisifier(List<Byte> exported) => ImportFromBinary(exported);
        public Noisifier()
            => SetDefault();



        public Int32 PrimaryNoiseCount => _primaryNoise.Length;
        public Int32 ComplexNoiseCount => _complexNoise.Length;

        public string PrimaryNoise => _primaryNoise;
        public string ComplexNoise => _complexNoise;
        public List<char> Banned => _banned;

        public char RandomPrimaryChar => _primaryNoise[_random.Next(PrimaryNoiseCount)];
        public char RandomComplexChar => _complexNoise[_random.Next(ComplexNoiseCount)];

        public string RandomPrimarySequence(Int32 count) =>
            string.Concat(Enumerable.Range(0, count).Select
            (
                _ => _primaryNoise[_random.Next(PrimaryNoiseCount)]
            )
        );
        public string RandomComplexSequence(Int32 count) =>
            string.Concat(Enumerable.Range(0, count).Select
            (
                _ => _complexNoise[_random.Next(ComplexNoiseCount)]
            )
        );





        static public bool IsPrimaryNoiseValidForKey(Template.IEncryptionKey reKey, string primaryNoise, bool throwException = false)
            => IsPrimaryNoiseValidForKey(reKey.FinalAlphabet, primaryNoise, throwException);
        static public bool IsPrimaryNoiseValidForKey(string exAlphabet, string primaryNoise, bool throwException = false)
        {
            return IsNoiseValid
            (
                exAlphabet,
                primaryNoise,
                new ArgumentException
                (
                    $"PrimaryNoise bytes can not overlap with ExternalAlphabet chars",
                    nameof(primaryNoise)
                ),
                throwException
            );
        }
        static public bool IsPrimaryNoiseValidForMessage(string message, string primaryNoise, bool throwException = false)
        {
            return IsNoiseValid
            (
                message,
                primaryNoise,
                new ArgumentException
                (
                    $"PrimaryNoise bytes can not overlap with message chars",
                    nameof(primaryNoise)
                ),
                throwException
            );
        }

        public bool IsPrimaryNoiseValidForKey(Template.IEncryptionKey reKey, bool throwException = false)
            => IsPrimaryNoiseValidForKey(reKey.FinalAlphabet, _primaryNoise, throwException);
        public bool IsPrimaryNoiseValidForKey(string exAlphabet, bool throwException = false)
            => IsPrimaryNoiseValidForKey(exAlphabet, _primaryNoise, throwException);
        public bool IsPrimaryNoiseValidForMessage(string message, bool throwException = false)
            => IsPrimaryNoiseValidForMessage(message, _primaryNoise, throwException);


        static public bool IsComplexNoiseValidForKey(Template.IEncryptionKey reKey, string complexNoise, bool throwException = false)
            => IsComplexNoiseValidForKey(reKey.FinalAlphabet, complexNoise, throwException);
        static public bool IsComplexNoiseValidForKey(string exAlphabet, string complexNoise, bool throwException = false)
        {
            return IsNoiseValid
            (
                exAlphabet,
                complexNoise,
                new ArgumentException
                (
                    $"PrimaryNoise bytes can not overlap with ExternalAlphabet chars",
                    nameof(complexNoise)
                ),
                throwException
            );
        }
        static public bool IsComplexNoiseValidForMessage(string message, string complexNoise, bool throwException = false)
        {
            return IsNoiseValid
            (
                message,
                complexNoise,
                new ArgumentException
                (
                    $"PrimaryNoise bytes can not overlap with message chars",
                    nameof(complexNoise)
                ),
                throwException
            );
        }

        public bool IsComplexNoiseValidForKey(Template.IEncryptionKey reKey, bool throwException = false)
            => IsComplexNoiseValidForKey(reKey.FinalAlphabet, _complexNoise, throwException);
        public bool IsComplexNoiseValidForKey(string exAlphabet, bool throwException = false)
            => IsComplexNoiseValidForKey(exAlphabet, _complexNoise, throwException);
        public bool IsComplexNoiseValidForMessage(string message, bool throwException = false)
            => IsComplexNoiseValidForMessage(message, _complexNoise, throwException);



        static private bool IsNoiseValid(string exAlphabet_or_message, string primaryNoise_or_complexNoise,
            ArgumentException errorMessage, bool throwException = false)
        {
            foreach (char noiseChar in primaryNoise_or_complexNoise)
            {
                if (exAlphabet_or_message.Contains(noiseChar))
                {
                    if (throwException) throw new ArgumentException
                        (
                            errorMessage.Message +
                            $"\nDuplicate char: {noiseChar}",
                            errorMessage.ParamName
                        );
                    return false;
                }
            }
            return true;
        }





        public void Next(bool throwExceptions = true)
        {
            try { GenerateAll(); }
            catch { if (throwExceptions) throw; }
        }
        public void Next(List<char> bannedForFailsafeRegeneration,
            bool resetSettingsToDefaultIfFailed = true, bool throwExceptions = true)
        {
            try
            {
                GenerateAll();
            }
            catch
            {
                if (resetSettingsToDefaultIfFailed)
                {
                    try
                    {
                        DefaultGenerate(bannedForFailsafeRegeneration);
                    }
                    catch
                    {
                        if (throwExceptions) throw;
                    }
                }
                else if (throwExceptions) throw;
            }
        }



        public bool ImportFromString(string data, bool throwExceptions = false)
        {
            try
            {
                Int32 splitterId = data.IndexOf(':'), offset, parsedLength;

                if (splitterId == -1)
                {
                    if (throwExceptions)
                        throw new ArgumentException
                        (
                            $"Data doesnt contain splitter for determining PrimaryNoise length" +
                            $"\ndata.IndexOf(':') == -1",
                            nameof(data) + "," + nameof(splitterId)
                        );
                    return false;
                }
                else if (!Int32.TryParse(data.AsSpan(0, splitterId), out parsedLength))
                {
                    if (throwExceptions)
                        throw new ArgumentException
                        (
                            $"Unable to parse PrimaryNoise length" +
                            $"\nExpected length to be at indexes 0-{splitterId}" +
                            $"\nInvalid sequence: {data[..splitterId]}",
                            nameof(data) + "," + nameof(splitterId)
                        );
                    return false;
                }
                else if (data.Length < splitterId + 1 + parsedLength + 4)
                {
                    if (throwExceptions)
                        throw new ArgumentException
                        (
                            $"Data is insufficient for expected PrimaryNoise & smallest possible ComplexNoise" +
                            $"Data length: {data.Length}   <   expected: {splitterId + 1 + parsedLength + 4}",
                            nameof(data) + "," + nameof(splitterId) + "," + nameof(parsedLength)
                        );
                    return false;
                }

                _primaryNoise = data.Substring(splitterId + 1, parsedLength);


                offset = splitterId + 1 + parsedLength;
                splitterId = data.IndexOf(':', offset);

                if (splitterId == -1)
                {
                    if (throwExceptions)
                        throw new ArgumentException
                        (
                            $"Data doesnt contain another splitter for determining ComplexNoise length" +
                            $"\ndata.IndexOf(':') == -1",
                            nameof(data) + "," + nameof(splitterId)
                        );
                    return false;
                }
                else if (!Int32.TryParse(data.AsSpan(offset, splitterId - offset), out parsedLength))
                {
                    if (throwExceptions)
                        throw new ArgumentException
                        (
                            $"Unable to parse ComplexNoise length" +
                            $"\nExpected length to be at indexes {offset}-{splitterId}" +
                            $"\nInvalid sequence: {data[offset..]}",
                            nameof(data) + "," + nameof(splitterId)
                        );
                    return false;
                }
                else if (data.Length < splitterId + 1 + parsedLength)
                {
                    if (throwExceptions)
                        throw new ArgumentException
                        (
                            $"Data is insufficient for expected ComplexNoise" +
                            $"Data length: {data.Length}   <   expected: {splitterId + 1 + parsedLength}",
                            nameof(data) + "," + nameof(splitterId) + "," + nameof(parsedLength)
                        );
                    return false;
                }

                _complexNoise = data.Substring(splitterId + 1, parsedLength);
            }
            catch
            {
                if (throwExceptions) throw;
                return false;
            }
            return true;
        }
        public string ExportAsString()
            => _primaryNoise.Length + ":" + _primaryNoise +
               _complexNoise.Length + ":" + _complexNoise;

        public bool ImportFromBinary(List<Byte> data, bool throwExceptions = false)
        {
            try
            {
                Int32 primaryCount = FromBinary.BigEndian<Int32>
                (
                    [..
                        data.GetRange(0, 4)
                    ]
                );


                if (data.Count < primaryCount + 8)
                {
                    if (throwExceptions)
                        throw new ArgumentException
                        (
                            $"Data length is insufficient for the specified primaryNoiseCount" +
                            $" {primaryCount + 8} from data[0-4]",
                            nameof(data)
                        );
                    return false;
                }


                _primaryNoise = FromBinary.Utf16
                (
                    data.GetRange
                    (
                        4,
                        primaryCount
                    )
                );


                Int32 complexCount = FromBinary.BigEndian<Int32>
                (
                    [..
                        data.GetRange(primaryCount + 4, 4)
                    ]
                );

                if (data.Count < complexCount + primaryCount + 8)
                {
                    if (throwExceptions)
                        throw new ArgumentException
                        (
                            $"Data length is insufficient for the specified complexNoiseCount" +
                            $" {complexCount + primaryCount + 8}" +
                            $"from data[{primaryCount + 4}-{primaryCount + 8}]",
                            nameof(data)
                        );
                    return false;
                }


                _complexNoise = FromBinary.Utf16
                (
                    data.GetRange
                    (
                        primaryCount + 8,
                        complexCount
                    )
                );
            }
            catch
            {
                if (throwExceptions) throw;
                return false;
            }
            return true;
        }
        public List<Byte> ExportAsBinary()
        {
            Byte[] exportedPrimary = ToBinary.Utf16(_primaryNoise);
            Byte[] exportedComplex = ToBinary.Utf16(_complexNoise);

            return
            [
                .. ToBinary.BigEndian(exportedPrimary.Length),
                .. exportedPrimary,

                .. ToBinary.BigEndian(exportedComplex.Length),
                .. exportedComplex
            ];
        }



        public void SetDefault(List<char> banned, Int32 primaryCount, Int32 complexCount)
        {
            _banned.Clear();
            _banned.AddRange(banned);

            SetDefault(primaryCount, complexCount);
        }
        public void SetDefault(Int32 primaryCount = 8, Int32 complexCount = 16)
        {
            _primaryCount = primaryCount;
            _complexCount = complexCount;
        }
        public void SetDefault(List<char> banned)
        {
            _banned.Clear();
            _banned.AddRange(banned);
        }

        public void SetDefaultOnlyPr(Int32 primaryCount = 8)
            => _primaryCount = primaryCount;
        public void SetDefaultOnlyCplx(Int32 complexCount = 16)
            => _complexCount = complexCount;

        public void DefaultGenerate(List<char> banned)
        {
            SetDefault(banned);
            GenerateAll();
        }
        public void CopyFrom(Noisifier otherNoisifier, bool fullCopy = true)
        {
            Set(otherNoisifier.PrimaryNoise, otherNoisifier.ComplexNoise);

            if (fullCopy)
                SetDefault
                (
                    otherNoisifier.Banned,
                    otherNoisifier._primaryCount,
                    otherNoisifier._complexCount
                );
        }
        private void Set(string primaryNoise, string complexNoise)
        {
            _primaryNoise = primaryNoise;
            _complexNoise = complexNoise;
        }



        private void GenerateAll()
        {
            GeneratePrimary(false);
            GenerateComplex(true);
        }



        private void ReconfigureNoiseParametersCount(Int32 allowedTotal)
        {
            if (allowedTotal < _primaryCount + _complexCount)
            {
                Int32 compromiseLeft = allowedTotal / 3;
                _primaryCount = compromiseLeft;
                _complexCount = allowedTotal - compromiseLeft;
            }
        }
        private List<char> GetRemainingAllowed(List<char> banned, Int32 targetCount, bool banAlreadyUsed)
        {
            List<char> result = [.. DEFAULT.CHARACTERS.WITHOUT_SPACE];

            if (!banAlreadyUsed) ReconfigureNoiseParametersCount(256 - banned.Count);
            else foreach (char bannedChar in _primaryNoise == ""
                    ? _complexNoise : _primaryNoise)
                    result.RemoveAll(c => c == bannedChar);

            foreach (char bannedChar in banned)
                result.RemoveAll(c => c == bannedChar);


            Int32 chosenId, curCount = result.Count;
            while (curCount > targetCount)
            {
                chosenId = _random.Next(curCount);

                result.RemoveRange
                (
                    chosenId,
                    Math.Min
                    (
                        curCount - chosenId - 1,
                        _random.Next(1, curCount - targetCount)
                    )
                );

                curCount = result.Count;
            }

            return result;
        }



        public string GenerateNoise(int count, List<char> allowed)
        {
            if (count <= 0) return string.Empty;
            if (count > allowed.Count) throw new ArgumentOutOfRangeException
                (
                    $"Count is greater than max possible length: {allowed.Count}"
                );

            StringBuilder result = new(count);
            Int32 totalCount = allowed.Count;

            for (var lastUsedId = 0; lastUsedId < count; lastUsedId++)
            {
                Int32 chosenUnused = _random.Next(lastUsedId, totalCount);

                (allowed[lastUsedId], allowed[chosenUnused]) =
                (allowed[chosenUnused], allowed[lastUsedId]);

                result.Append(allowed[lastUsedId]);
            }

            return result.ToString();
        }



        public void GeneratePrimary(List<char> banned, bool banAlreadyUsedInComplex)
        {
            //  Important to get allowed separately from GenerateNoise
            //  because _primaryCount can change here in default fail case
            _primaryNoise = "";
            List<char> allowed = GetRemainingAllowed(banned, _primaryCount, banAlreadyUsedInComplex);

            _primaryNoise = GenerateNoise(_primaryCount, allowed);
        }
        public void GeneratePrimary(bool banAlreadyUsedInComplex)
            => GeneratePrimary(_banned, banAlreadyUsedInComplex);

        public void GenerateComplex(List<char> banned, bool banAlreadyUsedInPrimary)
        {
            //  Important to get allowed separately from GenerateNoise
            //  because _complexCount can change here in default fail case
            _complexNoise = "";
            List<char> allowed = GetRemainingAllowed(banned, _complexCount, banAlreadyUsedInPrimary);

            _complexNoise = GenerateNoise(_complexCount, allowed);
        }
        public void GenerateComplex(bool banAlreadyUsedInPrimary)
            => GenerateComplex(_banned, banAlreadyUsedInPrimary);
    }
}