using System;
using System.Collections.Generic;


using AVcontrol;



namespace JabrAPI.Template
{
    abstract public class IBinaryKey
    {
        protected readonly SecureRandom _random = new(128);  //  Reseed after every 128 generated bytes (min possible amount)
        protected readonly BinaryNoisifier _noisifier = new();

        protected readonly List<Byte> _shifts = [0];
        protected Int32 _shCount = 0;



        public BinaryNoisifier Noisifier => _noisifier;

        virtual public ISetHelper? Set => null;
        virtual public IBinaryValidateHelper? IsValid => null;



        public List<Byte> Shifts => _shifts;
        public Int32 ShAmount => _shifts == null ? -1 : _shifts.Count;
        public Int32 ShLength => _shifts == null ? -1 : _shifts.Count;
        public Int32 ShCount  => _shifts == null ? -1 : _shifts.Count;

        abstract public List<Byte> FinalAlphabet { get; }



        public void Next(bool resetSettingsToDefaultIfFailed = true, bool throwExceptions = true)
        {
            try
            {
                GenerateAll();
            }
            catch
            {
                if (resetSettingsToDefaultIfFailed)
                {
                    try
                    {
                        DefaultGenerate();
                    }
                    catch
                    {
                        if (throwExceptions) throw;
                    }
                }
                else if (throwExceptions) throw;
            }
        }



        abstract public bool ImportFromBinary(List<Byte> data, bool throwExceptions = false);

        abstract public List<Byte> ExportAsBinary();



        protected void DefaultGenerate()
        {
            Set!.Default();
            GenerateAll();
        }
        abstract protected private void GenerateAll();



        public void GenerateRandomShifts(Int32 count, Byte minVal, Byte maxVal)
        {
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException
                (
                    nameof(count),
                    "count cannot be negative"
                );
            }
            else if (minVal > maxVal)
            {
                throw new ArgumentException
                (
                    "min value cannot be greater than max value",
                    "minVal, maxVal"
                );
            }
            else if (minVal < 0)
            {
                throw new ArgumentOutOfRangeException
                (
                    nameof(minVal),
                    "minVal cannot be negative"
                );
            }

            _shifts.Clear();
            if (count == 0)
            {
                _shifts.Add(0);
                return;
            }

            for (var curId = 0; curId < count; curId++)
                _shifts.Add(_random.Next(minVal, maxVal));
        }
        public void GenerateRandomShifts(Byte minVal, Byte maxVal)
            => GenerateRandomShifts(_random.Next(256, 512), minVal, maxVal);
    }
}