using System;
using System.Collections.Generic;


using AVcontrol;
using JabrAPI.Noise;



namespace JabrAPI
{
    public partial class BinaryNoisifier
    {
        private readonly SecureRandom _random = new(128);  //  Reseed after every 128 generated bytes (min possible amount)
        public BinaryNoiseSettings settings = new();

        private readonly SetHelper _setHelper;
        private readonly ValidateHelper _validateHelper;

        private readonly List<Byte> _primaryNoise = [];
        private readonly List<Byte> _complexNoise = [];

        private readonly List<Byte> _banned = [];
        private Byte _primaryCount = 8;
        private Byte _complexCount = 16;



        public BinaryNoisifier(List<Byte> primaryNoise, List<Byte> complexNoise)
        {
            _setHelper = new(this);
            _validateHelper = new(this);

            CopyFrom(primaryNoise, complexNoise);
        }
        public BinaryNoisifier(BinaryNoisifier otherNoisifier, bool fullCopy = true)
        {
            _setHelper = new(this);
            _validateHelper = new(this);

            CopyFrom(otherNoisifier, fullCopy);
        }

        public BinaryNoisifier(bool autoGenerate, List<Byte> banned)
        {
            _setHelper = new(this);
            _validateHelper = new(this);

            if (autoGenerate) DefaultGenerate(banned);
            else Set.Default(banned);
        }

        public BinaryNoisifier(List<Byte> binaryExportData, bool throwExceptions = false)
        {
            _setHelper = new(this);
            _validateHelper = new(this);

            ImportFromBinary(binaryExportData, throwExceptions);
        }
        public BinaryNoisifier()
        {
            _setHelper = new(this);
            _validateHelper = new(this);
        }
    }
}